Delete video endpoint
efonsecab/FairPlayTube pull request #272
Opened 2021-08-03 04:37 UTC by LuisiitoDev

### Checklist

- [ ] Created/Updated Automated Test(s) for the related controller(s)
- [ ] Verified all Automated Tests are passing locally.
- [ ] Added reviewer(s)
- [ ] Referenced the related Issue/Task

### Description
It was created the endpoint for deleting a video
it was created the delete method inside VideoService

## Related Issue
https://github.com/efonsecab/FairPlayTube/issues/38

2021-08-03 15:29 UTC, efonsecab requested changes

2021-08-03 15:29 UTC, efonsecab commented on src/FairPlayTubeSln/FairPlayTube.Controllers/VideoController.cs
> +            await VideoService.DeleteVideoAsync(videoId, userObjectId, cancellationToken);
@LuisiitoDev 
Needs to validate if the user is the video's owner.
Check the logic on the other endpoints.
If the user is not an owner of the video throw an exception with the following message
"Delete denied. You are not an owner of this video".

2021-08-03 18:43 UTC, LuisiitoDev commented on src/FairPlayTubeSln/FairPlayTube.Controllers/VideoController.cs
> +            await VideoService.DeleteVideoAsync(videoId, userObjectId, cancellationToken);
gotcha!, I'll do it and update the PR, thanks.

2021-08-07 00:00 UTC, efonsecab requested changes

2021-08-07 00:27 UTC, LuisiitoDev commented on src/FairPlayTubeSln/FairPlayTube.Controllers/VideoController.cs
> +            await VideoService.DeleteVideoAsync(videoId, userObjectId, cancellationToken);
Sure, I'm gonna do it, thanks

2021-08-07 01:03 UTC, LuisiitoDev commented on src/FairPlayTubeSln/FairPlayTube.Controllers/VideoController.cs
> +            await VideoService.DeleteVideoAsync(videoId, userObjectId, cancellationToken);
Done, I have applied the changes required.

2021-08-07 12:55 UTC, efonsecab requested changes

2021-08-07 12:55 UTC, efonsecab commented on src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
> +            if (!videoEntity.ApplicationUser.AzureAdB2cobjectId.ToString().Equals(userAzureAdB2cObjectId))
Move this logic to the controller, the VideoService must not have context knowledge in order to be reusable.
The onwership validation logic must be in the controller and use the IsVideoOwner method.
Check the "GetVideoEditAccessToken" endpoint to see an example

2021-08-08 19:42 UTC, LuisiitoDev commented on src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
> +            if (!videoEntity.ApplicationUser.AzureAdB2cobjectId.ToString().Equals(userAzureAdB2cObjectId))
Done.

2021-08-10 17:36 UTC, efonsecab approved these changes

2021-08-10 17:37 UTC, merged