it was created the send message method inside the UserClientService t…
efonsecab/FairPlayTube pull request #295
Opened 2021-08-07 01:27 UTC by LuisiitoDev

…o call the SendMessage from the user controller

### Checklist

- [ ] Created/Updated Automated Test(s) for the related controller(s)
- [ ] Verified all Automated Tests are passing locally.
- [ ] Added reviewer(s)
- [ ] Referenced the related Issue/Task

### Description
It was created the SendMessageAsync inside the UserClientService

## Related Issue
https://github.com/efonsecab/FairPlayTube/issues/210

2021-08-07 12:59 UTC, efonsecab requested changes

2021-08-07 12:59 UTC, efonsecab commented on src/FairPlayTubeSln/FairPlayTube.ClientServices/UserClientService.cs
> +            var authorizedHttpClient = this.HttpClientService.CreateAnonymousClient();
this is not creating the authorized client

2021-08-08 20:10 UTC, LuisiitoDev commented on src/FairPlayTubeSln/FairPlayTube.ClientServices/UserClientService.cs
> +            var authorizedHttpClient = this.HttpClientService.CreateAnonymousClient();
Done.

2021-08-10 17:40 UTC, efonsecab approved these changes

2021-08-10 17:41 UTC, merged